import type { StoreState } from "@/lib/types";

export function createSeedState(): StoreState {
  return {
    roles: [
      {
        id: "role-admin",
        key: "admin",
        name: "Admin",
        permissions: ["all"],
      },
      {
        id: "role-manager",
        key: "manager",
        name: "Manager",
        permissions: ["inventory.read", "inventory.write", "inventory.approve"],
      },
      {
        id: "role-staff",
        key: "staff",
        name: "Staff",
        permissions: ["inventory.read", "inventory.write.request"],
      },
    ],
    users: [
      {
        id: "user-1",
        name: "Chanchai",
        email: "admin@stock.local",
        lineUserId: "U-admin",
        roleId: "role-admin",
        active: true,
      },
      {
        id: "user-2",
        name: "Warehouse Manager",
        email: "manager@stock.local",
        lineUserId: "U-manager",
        roleId: "role-manager",
        active: true,
      },
      {
        id: "user-3",
        name: "Inventory Staff",
        email: "staff@stock.local",
        lineUserId: "U-staff",
        roleId: "role-staff",
        active: true,
      },
    ],
    products: [
      {
        id: "prd-001",
        sku: "SKU-001",
        name: "นม UHT 1 ลิตร",
        category: "เครื่องดื่ม",
        unit: "กล่อง",
        location: "Main Warehouse",
        currentStock: 18,
        lowStockThreshold: 20,
        reorderPoint: 30,
        active: true,
        createdAt: new Date("2026-06-15T09:00:00.000Z").toISOString(),
        updatedAt: new Date("2026-06-15T12:32:00.000Z").toISOString(),
      },
      {
        id: "prd-002",
        sku: "SKU-002",
        name: "น้ำดื่มแพ็ค",
        category: "เครื่องดื่ม",
        unit: "แพ็ค",
        location: "Main Warehouse",
        currentStock: 120,
        lowStockThreshold: 40,
        reorderPoint: 60,
        active: true,
        createdAt: new Date("2026-06-15T09:00:00.000Z").toISOString(),
        updatedAt: new Date("2026-06-15T09:00:00.000Z").toISOString(),
      },
      {
        id: "prd-003",
        sku: "SKU-003",
        name: "กระดาษ A4",
        category: "สำนักงาน",
        unit: "รีม",
        location: "Main Warehouse",
        currentStock: 22,
        lowStockThreshold: 25,
        reorderPoint: 50,
        active: true,
        createdAt: new Date("2026-06-15T09:00:00.000Z").toISOString(),
        updatedAt: new Date("2026-06-15T14:10:00.000Z").toISOString(),
      },
      {
        id: "prd-004",
        sku: "SKU-004",
        name: "สบู่เหลวล้างมือ",
        category: "อุปกรณ์ทำความสะอาด",
        unit: "ขวด",
        location: "Main Warehouse",
        currentStock: 47,
        lowStockThreshold: 15,
        reorderPoint: 30,
        active: true,
        createdAt: new Date("2026-06-15T09:00:00.000Z").toISOString(),
        updatedAt: new Date("2026-06-15T09:00:00.000Z").toISOString(),
      },
    ],
    movements: [
      {
        id: "mov-001",
        productId: "prd-002",
        type: "IN",
        quantity: 60,
        stockAfter: 120,
        note: "รับเข้าเริ่มต้น",
        reason: "seed data",
        status: "approved",
        createdById: "user-1",
        approvedById: "user-1",
        source: "seed",
        createdAt: new Date("2026-06-15T09:00:00.000Z").toISOString(),
        updatedAt: new Date("2026-06-15T09:00:00.000Z").toISOString(),
      },
      {
        id: "mov-002",
        productId: "prd-001",
        type: "OUT",
        quantity: 12,
        stockAfter: 18,
        note: "ขายหน้าร้าน",
        reason: "seed data",
        status: "approved",
        createdById: "user-3",
        approvedById: "user-2",
        source: "seed",
        createdAt: new Date("2026-06-15T12:30:00.000Z").toISOString(),
        updatedAt: new Date("2026-06-15T12:30:00.000Z").toISOString(),
      },
      {
        id: "mov-003",
        productId: "prd-003",
        type: "OUT",
        quantity: 8,
        stockAfter: 22,
        note: "ใช้ในออฟฟิศ",
        reason: "seed data",
        status: "approved",
        createdById: "user-2",
        approvedById: "user-2",
        source: "seed",
        createdAt: new Date("2026-06-15T14:10:00.000Z").toISOString(),
        updatedAt: new Date("2026-06-15T14:10:00.000Z").toISOString(),
      },
    ],
    notifications: [
      {
        id: "noti-001",
        kind: "LOW_STOCK",
        status: "open",
        title: "สินค้าต่ำกว่าจุดแจ้งเตือน",
        message: "นม UHT 1 ลิตร เหลือ 18 กล่อง ต่ำกว่าค่า threshold 20 กล่อง",
        productId: "prd-001",
        recipientId: "user-2",
        channel: "line",
        dedupeKey: "low-stock:prd-001",
        sentAt: new Date("2026-06-15T12:32:00.000Z").toISOString(),
        createdAt: new Date("2026-06-15T12:32:00.000Z").toISOString(),
        updatedAt: new Date("2026-06-15T12:32:00.000Z").toISOString(),
      },
    ],
    lineIntegration: {
      id: "line-001",
      channelName: "My Stock OA",
      webhookEnabled: false,
      autoApproveStock: true,
    },
  };
}
